version: "3.5"

services:
  api01: &api
    image: 'abrxu/rinhadebackend-spring:latest'
    hostname: api01
    environment:
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinhadebackend_spring
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "183MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinhadebackend_spring
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "183MB"

  db:
    image: postgres:16.6-alpine
    hostname: db
    environment:
      - POSTGRES_DB=rinhadebackend_spring
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "183MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1